# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Outdoors Club
email: toc@ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  Send It! We help UCSD folks get outside for whatever that means to them.
  Members have free gear rentals and connections to great outdoor excursions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "toc.ucsd.edu" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: alembic-jekyll-theme

navigation_header:
  Home: /
  About: /about
  Join: /join
  Staff: /staff
  Trips: /trips

navigation_footer:
  Home: /
  About: /about
  Join: /join
  Staff: /staff
  Trips: /trips

plugins:
  - jekyll-seo-tag

google_analytics: UA-140785853-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
